(()=>{
'use strict';
const API='https://papachiz-music-7948828570.papachiz-music.workers.dev';
const $=id=>document.getElementById(id);
const audio=$('audio'), title=$('title'), artist=$('artist'), cover=$('cover'), current=$('current'), duration=$('duration'), seek=$('seek'), play=$('play'), prev=$('prev'), next=$('next'), shuffle=$('shuffle'), repeat=$('repeat'), open=$('songs-open'), close=$('songs-close'), panel=$('playlist'), list=$('track-list'), tc=$('track-count'), pc=$('playlist-count');
let tracks=[], index=0, shuffleOn=false, repeatOn=false;
const PLAY='<svg viewBox="0 0 24 24"><path d="M8 5v14l11-7L8 5Z"/></svg>';
const PAUSE='<svg viewBox="0 0 24 24"><path d="M7 5h4v14H7V5Zm6 0h4v14h-4V5Z"/></svg>';
const fmt=v=>Number.isFinite(v)?`${Math.floor(v/60)}:${Math.floor(v%60).toString().padStart(2,'0')}`:'0:00';
const name=t=>t?.title||'Без названия'; const by=t=>t?.artist||'PAPACHIZ123';
function sync(){play.innerHTML=audio.paused?PLAY:PAUSE;play.title=audio.paused?'Воспроизвести':'Пауза';play.setAttribute('aria-label',play.title)}
function paint(t){title.textContent=name(t);artist.textContent=by(t);cover.src=t?.cover&&/^https:\/\//i.test(t.cover)?t.cover:'profile.jpg'}
function render(){list.innerHTML='';const n=tracks.length;tc.textContent=n;pc.textContent=`${n} ${n===1?'трек':(n>=2&&n<=4)?'трека':'треков'}`;if(!n){const li=document.createElement('li');li.className='empty';li.textContent='Плейлист пока пуст.';list.append(li);return;}tracks.forEach((t,i)=>{const li=document.createElement('li');const b=document.createElement('button');b.type='button';b.className='track'+(i===index?' active':'');const no=document.createElement('span');no.className='num';no.textContent=String(i+1).padStart(2,'0');const cp=document.createElement('span');cp.className='track-copy';const s=document.createElement('strong');s.textContent=name(t);const sm=document.createElement('small');sm.textContent=by(t);cp.append(s,sm);const tm=document.createElement('span');tm.className='track-time';tm.textContent=Number.isFinite(Number(t.duration))?fmt(Number(t.duration)):'▶';b.append(no,cp,tm);b.addEventListener('click',()=>{load(i,true);panel.hidden=true});li.append(b);list.append(li);});}
function nextIndex(){if(!shuffleOn||tracks.length<2)return index+1;let n=index;while(n===index)n=Math.floor(Math.random()*tracks.length);return n;}
function load(i,auto=false){if(!tracks.length)return;index=(i+tracks.length)%tracks.length;const t=tracks[index];paint(t);if(audio.src!==t.src){audio.src=t.src;seek.value=0;current.textContent='0:00';duration.textContent=Number.isFinite(Number(t.duration))?fmt(Number(t.duration)):'0:00'}render();if(auto)audio.play().catch(()=>{});}
play.addEventListener('click',()=>audio.paused?audio.play().catch(()=>{}):audio.pause());prev.addEventListener('click',()=>load(index-1,true));next.addEventListener('click',()=>load(nextIndex(),true));shuffle.addEventListener('click',()=>{shuffleOn=!shuffleOn;shuffle.classList.toggle('active',shuffleOn)});repeat.addEventListener('click',()=>{repeatOn=!repeatOn;repeat.classList.toggle('active',repeatOn)});seek.addEventListener('input',()=>{if(Number.isFinite(audio.duration))audio.currentTime=Number(seek.value)});open.addEventListener('click',()=>panel.hidden=false);close.addEventListener('click',()=>panel.hidden=true);panel.addEventListener('click',e=>{if(e.target===panel)panel.hidden=true});document.addEventListener('keydown',e=>{if(e.key==='Escape')panel.hidden=true});audio.addEventListener('play',sync);audio.addEventListener('pause',sync);audio.addEventListener('loadedmetadata',()=>{seek.max=Number.isFinite(audio.duration)?audio.duration:1;duration.textContent=fmt(audio.duration)});audio.addEventListener('timeupdate',()=>{if(!Number.isFinite(audio.duration))return;seek.max=audio.duration;seek.value=audio.currentTime;current.textContent=fmt(audio.currentTime);duration.textContent=fmt(audio.duration)});audio.addEventListener('ended',()=>{if(repeatOn){audio.currentTime=0;audio.play().catch(()=>{})}else load(nextIndex(),true)});
fetch(API.replace(/\/$/,'')+'/playlist',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(data=>{tracks=Array.isArray(data?.tracks)?data.tracks.filter(t=>t&&typeof t.src==='string'&&/^https:\/\//i.test(t.src)):[];if(!tracks.length){title.textContent='Плейлист пуст';artist.textContent='PAPACHIZ123';render();return;}load(0,false);}).catch(()=>{title.textContent='Музыка недоступна';artist.textContent='PAPACHIZ123';render();});sync();
})();
